// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjpuoxwucuimwstlxpre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqcHVveHd1Y3VpbXdzdGx4cHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTI1MjAsImV4cCI6MjA2OTM4ODUyMH0.D6MVagnzqpFVb0__lrbTYmDY6k6hScKb8sXnV5lsdQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});